-- ============================================================================
-- Closed-Loop System: project_entities + closed_loop_state
-- ============================================================================
-- Adds:
--   1. project_entities table — GCM canonical entity references
--   2. closed_loop_state JSONB column on video_projects
--   3. worker_prompts JSONB column on video_projects
--   4. creative_manifest JSONB column on video_projects
-- ============================================================================

-- 1. Project Entities table (GCM)
CREATE TABLE IF NOT EXISTS public.project_entities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES public.video_projects(id) ON DELETE CASCADE,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('character', 'setting', 'prop', 'style')),
  name TEXT NOT NULL,
  reference_url TEXT,
  text_description TEXT NOT NULL DEFAULT '',
  attributes JSONB NOT NULL DEFAULT '{}',
  appearance_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for fast entity lookups by project
CREATE INDEX IF NOT EXISTS idx_project_entities_project_id
  ON public.project_entities(project_id);

-- RLS policies
ALTER TABLE public.project_entities ENABLE ROW LEVEL SECURITY;

-- Users can read entities belonging to their own video projects
CREATE POLICY "Users can read own project entities"
  ON public.project_entities FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.video_projects vp
      WHERE vp.id = project_entities.project_id
        AND vp.user_id = auth.uid()
    )
  );

-- Users can insert entities for their own video projects
CREATE POLICY "Users can insert own project entities"
  ON public.project_entities FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.video_projects vp
      WHERE vp.id = project_entities.project_id
        AND vp.user_id = auth.uid()
    )
  );

-- Users can update entities belonging to their own video projects
CREATE POLICY "Users can update own project entities"
  ON public.project_entities FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.video_projects vp
      WHERE vp.id = project_entities.project_id
        AND vp.user_id = auth.uid()
    )
  );

-- Users can delete entities belonging to their own video projects
CREATE POLICY "Users can delete own project entities"
  ON public.project_entities FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.video_projects vp
      WHERE vp.id = project_entities.project_id
        AND vp.user_id = auth.uid()
    )
  );

-- Service role bypass for workers
CREATE POLICY "Service role full access to project_entities"
  ON public.project_entities FOR ALL
  USING (auth.role() = 'service_role');

-- 2. Add closed-loop columns to video_projects
ALTER TABLE public.video_projects
  ADD COLUMN IF NOT EXISTS closed_loop_state JSONB DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS worker_prompts JSONB DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS creative_manifest JSONB DEFAULT NULL;

COMMENT ON COLUMN public.video_projects.closed_loop_state IS
  'Orchestrator state for crash recovery: phase, status, per-phase progress, flagged shots, errors';
COMMENT ON COLUMN public.video_projects.worker_prompts IS
  'Per-worker system prompts generated by the Orchestrator for this video';
COMMENT ON COLUMN public.video_projects.creative_manifest IS
  'User preferences + style rules merged from user profile and per-video overrides';
