/**
 * Video Editor Stores - Public API
 * 
 * The unified VideoEditorStore is the single source of truth for all video editor state.
 */

export {
  useVideoEditorStore,
  useVideoEditorActions,
  useIsDraggingType,
  useIsDraggingTransition,
  getVideoEditorState,
  startEffectDrag,
  startVideoTransitionDrag,
  startAudioTransitionDrag,
  startMaskDrag,
  startMediaDrag,
  startTextPresetDrag,
  startShapePresetDrag,
  getCurrentDrag,
  endDrag,
  // Selectors
  selectTracks,
  selectTrackById,
  selectVideoTracks,
  selectAudioTracks,
  selectClips,
  selectClipById,
  selectClipsByTrack,
  selectClipsInRange,
  selectTransitions,
  selectTransitionById,
  selectClipTransitions,
  selectSelectedClipIds,
  selectSelectedClipId,
  selectSelectedClip,
  selectSelectedTransitionId,
  selectSelectedTransition,
  selectPlayback,
  selectCurrentTime,
  selectCurrentFrame,
  selectIsPlaying,
  selectPlaybackRate,
  selectAspectRatio,
  selectResolution,
  selectPlayerDimensions,
  selectBackgroundColor,
  selectFps,
  selectEditMode,
  selectSnappingEnabled,
  selectShowAlignmentGuides,
  selectTrackHeight,
  selectClipHeight,
  selectProjectId,
  selectIsDirty,
  selectLastSavedAt,
  selectDurationInSeconds,
  selectDurationInFrames,
  selectActions,
  // Drag selectors (unified)
  selectDragState,
  selectDragType,
  selectIsDragging,
  selectIsDraggingType,
  selectDragVisuals,
  selectGhostElements,
  selectSnapLine,
  selectTrackInsertion,
  selectCommittedPositions,
  selectIsDraggingTransition,
  selectIsDraggingNewItem,
  selectIsDraggingClip,
} from './video-editor-store';

export type {
  VideoEditorStore,
  VideoEditorState,
  VideoEditorActions,
  AspectRatio,
  ResolutionPreset,
  TimelineTrack,
  TimelineClip,
  TransitionEntity,
  SelectionState,
  PlaybackState,
  UnifiedDragState,
  UnifiedDragType,
  DragVisualState,
  ClipDragSnapshot,
  SnapInfo,
  GhostElementData,
  CommittedDragPosition,
  EditMode,
  ClipType,
  TrackType,
} from './video-editor-store';
