/**
 * DevTools Media Store
 * ============================================================================
 * [DEVTOOLS-MEDIA] - This entire file supports DevTools media browsing.
 * Remove this file when the DevTools media integration is no longer needed.
 * Also remove references in:
 *   - GPUApiTester.tsx (search for [DEVTOOLS-MEDIA])
 *   - media-tab.tsx (search for [DEVTOOLS-MEDIA])
 *   - app/api/gpu-api/test/media/route.ts (delete entire file)
 *   - r2-storage.ts listFilesWithPrefix() (search for [DEVTOOLS-MEDIA])
 * ============================================================================
 *
 * Shared Zustand store for media generated by the GPU API Tester.
 * The Video Editor V2's MediaTab reads from this store to display
 * AI-generated assets in the asset panel.
 *
 * On first access, fetches ALL existing media from R2 via the API endpoint.
 * Also supports real-time additions from the current session.
 */

import { create } from 'zustand';

// ============================================================================
// TYPES
// ============================================================================

export interface DevToolsMediaItem {
  id: string;
  type: 'image' | 'video' | 'audio';
  url: string;
  name: string;
  createdAt: number; // timestamp
  width?: number;
  height?: number;
}

interface DevToolsMediaState {
  items: DevToolsMediaItem[];
  isLoading: boolean;
  hasFetched: boolean;
}

interface DevToolsMediaActions {
  addMedia: (item: Omit<DevToolsMediaItem, 'id' | 'createdAt'>) => void;
  removeMedia: (id: string) => void;
  clearMedia: () => void;
  fetchFromR2: () => Promise<void>;
}

type DevToolsMediaStore = DevToolsMediaState & DevToolsMediaActions;

// ============================================================================
// STORE
// ============================================================================

export const useDevToolsMediaStore = create<DevToolsMediaStore>()((set, get) => ({
  items: [],
  isLoading: false,
  hasFetched: false,

  addMedia: (item) => {
    const existing = get().items;
    // Deduplicate by URL
    if (existing.some((m) => m.url === item.url)) return;

    const newItem: DevToolsMediaItem = {
      ...item,
      id: crypto.randomUUID(),
      createdAt: Date.now(),
    };

    set({ items: [...existing, newItem] });
  },

  removeMedia: (id) => {
    set({ items: get().items.filter((m) => m.id !== id) });
  },

  clearMedia: () => {
    set({ items: [], hasFetched: false });
  },

  fetchFromR2: async () => {
    // Only fetch once per session
    if (get().hasFetched || get().isLoading) return;

    set({ isLoading: true });

    try {
      const response = await fetch('/api/gpu-api/test/media');
      const data = await response.json();

      if (data.success && Array.isArray(data.items)) {
        const existingUrls = new Set(get().items.map((m) => m.url));

        const newItems: DevToolsMediaItem[] = data.items
          .filter((item: DevToolsMediaItem) => !existingUrls.has(item.url))
          .map((item: DevToolsMediaItem) => ({
            id: item.id || crypto.randomUUID(),
            type: item.type,
            url: item.url,
            name: item.name,
            createdAt: item.createdAt || Date.now(),
          }));

        set({ items: [...get().items, ...newItems] });
      }
    } catch (error) {
      console.error('[DEVTOOLS-MEDIA] Failed to fetch media from R2:', error);
    } finally {
      set({ isLoading: false, hasFetched: true });
    }
  },
}));
