/**
 * Call to Action Templates
 * 
 * Animated CTAs for subscribe buttons, social follows, and engagement prompts.
 */

import { MotionGraphicsTemplate, MotionGraphicsCategory } from '../../types/motion-graphics';

export const ctaTemplates: MotionGraphicsTemplate[] = [
  {
    id: 'cta-subscribe',
    name: 'Subscribe Button',
    description: 'Animated YouTube-style subscribe button',
    category: MotionGraphicsCategory.CALL_TO_ACTION,
    tags: ['cta', 'subscribe', 'youtube', 'button'],
    duration: 120, // 4 seconds at 30fps
    isBuiltIn: true,
    editableProperties: [
      {
        id: 'buttonText',
        label: 'Button Text',
        type: 'text',
        value: 'SUBSCRIBE',
        defaultValue: 'SUBSCRIBE',
        group: 'Content',
      },
      {
        id: 'buttonColor',
        label: 'Button Color',
        type: 'color',
        value: '#FF0000',
        defaultValue: '#FF0000',
        group: 'Style',
      },
      {
        id: 'showBell',
        label: 'Show Bell Icon',
        type: 'boolean',
        value: true,
        defaultValue: true,
        group: 'Options',
      },
    ],
    remotionCode: `SubscribeCTA`,
  },
  {
    id: 'cta-like-comment',
    name: 'Like & Comment',
    description: 'Engagement prompt for likes and comments',
    category: MotionGraphicsCategory.CALL_TO_ACTION,
    tags: ['cta', 'like', 'comment', 'engagement'],
    duration: 90,
    isBuiltIn: true,
    editableProperties: [
      {
        id: 'buttonText',
        label: 'Text',
        type: 'text',
        value: 'LIKE & COMMENT',
        defaultValue: 'LIKE & COMMENT',
        group: 'Content',
      },
      {
        id: 'buttonColor',
        label: 'Color',
        type: 'color',
        value: '#3B82F6',
        defaultValue: '#3B82F6',
        group: 'Style',
      },
      {
        id: 'showBell',
        label: 'Show Icons',
        type: 'boolean',
        value: true,
        defaultValue: true,
        group: 'Options',
      },
    ],
    remotionCode: `SubscribeCTA`,
  },
  {
    id: 'cta-follow',
    name: 'Social Follow',
    description: 'Follow prompt with social media handle',
    category: MotionGraphicsCategory.SOCIAL_MEDIA,
    tags: ['cta', 'follow', 'social', 'instagram', 'tiktok'],
    duration: 105,
    isBuiltIn: true,
    editableProperties: [
      {
        id: 'handle',
        label: 'Handle',
        type: 'text',
        value: 'YourHandle',
        defaultValue: 'YourHandle',
        group: 'Content',
      },
      {
        id: 'platform',
        label: 'Platform',
        type: 'select',
        value: 'instagram',
        defaultValue: 'instagram',
        options: [
          { label: 'Instagram', value: 'instagram' },
          { label: 'TikTok', value: 'tiktok' },
          { label: 'Twitter/X', value: 'twitter' },
          { label: 'YouTube', value: 'youtube' },
        ],
        group: 'Content',
      },
      {
        id: 'primaryColor',
        label: 'Color',
        type: 'color',
        value: '#E1306C',
        defaultValue: '#E1306C',
        group: 'Style',
      },
    ],
    remotionCode: `SocialFollow`,
  },
  {
    id: 'cta-countdown',
    name: 'Countdown Timer',
    description: 'Animated countdown from any number',
    category: MotionGraphicsCategory.COUNTDOWN,
    tags: ['countdown', 'timer', 'intro', 'dramatic'],
    duration: 180, // 6 seconds for 5-second countdown + buffer
    isBuiltIn: true,
    editableProperties: [
      {
        id: 'startNumber',
        label: 'Start Number',
        type: 'number',
        value: 5,
        defaultValue: 5,
        min: 1,
        max: 10,
        group: 'Content',
      },
      {
        id: 'textColor',
        label: 'Number Color',
        type: 'color',
        value: '#FFFFFF',
        defaultValue: '#FFFFFF',
        group: 'Style',
      },
      {
        id: 'backgroundColor',
        label: 'Background',
        type: 'color',
        value: '#000000',
        defaultValue: '#000000',
        group: 'Style',
      },
    ],
    remotionCode: `CountdownTimer`,
  },
  {
    id: 'cta-swipe-up',
    name: 'Swipe Up',
    description: 'Stories-style swipe up CTA',
    category: MotionGraphicsCategory.CALL_TO_ACTION,
    tags: ['cta', 'swipe', 'stories', 'instagram', 'mobile'],
    duration: 90,
    isBuiltIn: true,
    editableProperties: [
      {
        id: 'buttonText',
        label: 'Text',
        type: 'text',
        value: 'SWIPE UP',
        defaultValue: 'SWIPE UP',
        group: 'Content',
      },
      {
        id: 'buttonColor',
        label: 'Color',
        type: 'color',
        value: '#FFFFFF',
        defaultValue: '#FFFFFF',
        group: 'Style',
      },
      {
        id: 'showBell',
        label: 'Show Arrow',
        type: 'boolean',
        value: true,
        defaultValue: true,
        group: 'Options',
      },
    ],
    remotionCode: `SubscribeCTA`,
  },
  {
    id: 'cta-link-bio',
    name: 'Link in Bio',
    description: 'Animated link in bio reminder',
    category: MotionGraphicsCategory.CALL_TO_ACTION,
    tags: ['cta', 'link', 'bio', 'social'],
    duration: 75,
    isBuiltIn: true,
    editableProperties: [
      {
        id: 'buttonText',
        label: 'Text',
        type: 'text',
        value: 'LINK IN BIO',
        defaultValue: 'LINK IN BIO',
        group: 'Content',
      },
      {
        id: 'buttonColor',
        label: 'Background',
        type: 'color',
        value: '#10B981',
        defaultValue: '#10B981',
        group: 'Style',
      },
      {
        id: 'showBell',
        label: 'Show Icon',
        type: 'boolean',
        value: true,
        defaultValue: true,
        group: 'Options',
      },
    ],
    remotionCode: `SubscribeCTA`,
  },
];
