/**
 * Title Card Templates
 * 
 * Full-screen title cards for intros, outros, and section transitions.
 */

import { MotionGraphicsTemplate, MotionGraphicsCategory } from '../../types/motion-graphics';

export const titleCardTemplates: MotionGraphicsTemplate[] = [
  {
    id: 'title-card-bold',
    name: 'Bold Title Card',
    description: 'Eye-catching full-screen title with animated entrance',
    category: MotionGraphicsCategory.TITLE_CARD,
    tags: ['title', 'intro', 'bold', 'full-screen'],
    duration: 90, // 3 seconds at 30fps
    isBuiltIn: true,
    editableProperties: [
      {
        id: 'title',
        label: 'Title',
        type: 'text',
        value: 'WELCOME',
        defaultValue: 'WELCOME',
        group: 'Content',
      },
      {
        id: 'subtitle',
        label: 'Subtitle',
        type: 'text',
        value: 'To Our Channel',
        defaultValue: 'To Our Channel',
        group: 'Content',
      },
      {
        id: 'backgroundColor',
        label: 'Background',
        type: 'color',
        value: '#1E1E1E',
        defaultValue: '#1E1E1E',
        group: 'Style',
      },
      {
        id: 'accentColor',
        label: 'Accent Color',
        type: 'color',
        value: '#F59E0B',
        defaultValue: '#F59E0B',
        group: 'Style',
      },
    ],
    remotionCode: `TitleCard`,
  },
  {
    id: 'title-card-minimal',
    name: 'Minimal Title',
    description: 'Clean, minimalist title card',
    category: MotionGraphicsCategory.TITLE_CARD,
    tags: ['title', 'minimal', 'clean', 'elegant'],
    duration: 75,
    isBuiltIn: true,
    editableProperties: [
      {
        id: 'title',
        label: 'Title',
        type: 'text',
        value: 'Chapter One',
        defaultValue: 'Chapter One',
        group: 'Content',
      },
      {
        id: 'subtitle',
        label: 'Subtitle',
        type: 'text',
        value: 'The Beginning',
        defaultValue: 'The Beginning',
        group: 'Content',
      },
      {
        id: 'backgroundColor',
        label: 'Background',
        type: 'color',
        value: '#FFFFFF',
        defaultValue: '#FFFFFF',
        group: 'Style',
      },
      {
        id: 'accentColor',
        label: 'Text Color',
        type: 'color',
        value: '#1F2937',
        defaultValue: '#1F2937',
        group: 'Style',
      },
    ],
    remotionCode: `TitleCard`,
  },
  {
    id: 'title-card-gradient',
    name: 'Gradient Title',
    description: 'Vibrant gradient background title card',
    category: MotionGraphicsCategory.TITLE_CARD,
    tags: ['title', 'gradient', 'colorful', 'modern'],
    duration: 90,
    isBuiltIn: true,
    editableProperties: [
      {
        id: 'title',
        label: 'Title',
        type: 'text',
        value: 'NEW VIDEO',
        defaultValue: 'NEW VIDEO',
        group: 'Content',
      },
      {
        id: 'subtitle',
        label: 'Subtitle',
        type: 'text',
        value: 'Watch Now',
        defaultValue: 'Watch Now',
        group: 'Content',
      },
      {
        id: 'backgroundColor',
        label: 'Background Start',
        type: 'color',
        value: '#6366F1',
        defaultValue: '#6366F1',
        group: 'Style',
      },
      {
        id: 'accentColor',
        label: 'Background End',
        type: 'color',
        value: '#EC4899',
        defaultValue: '#EC4899',
        group: 'Style',
      },
    ],
    remotionCode: `TitleCard`,
  },
  {
    id: 'title-card-episode',
    name: 'Episode Card',
    description: 'Perfect for podcast or series episodes',
    category: MotionGraphicsCategory.TITLE_CARD,
    tags: ['title', 'episode', 'podcast', 'series'],
    duration: 105,
    isBuiltIn: true,
    editableProperties: [
      {
        id: 'title',
        label: 'Episode Title',
        type: 'text',
        value: 'Episode 1',
        defaultValue: 'Episode 1',
        group: 'Content',
      },
      {
        id: 'subtitle',
        label: 'Episode Name',
        type: 'text',
        value: 'Getting Started',
        defaultValue: 'Getting Started',
        group: 'Content',
      },
      {
        id: 'backgroundColor',
        label: 'Background',
        type: 'color',
        value: '#0F172A',
        defaultValue: '#0F172A',
        group: 'Style',
      },
      {
        id: 'accentColor',
        label: 'Accent Color',
        type: 'color',
        value: '#22D3EE',
        defaultValue: '#22D3EE',
        group: 'Style',
      },
    ],
    remotionCode: `TitleCard`,
  },
];
